### PR TITLE
fix: give precedence to older rectangles when selecting or deleting

### LINKED ISSUE #41: New crop rectangles are created behind older ones
When a new crop rectangle is created, it will be put behind the others. So when this rectangle is overlapping with an already existing one it cannot be selected. This is not intuitive and doesn't behave that way in other apps. 
It would make more sense that the new rect is put in front of the others. 
Maybe it even makes sense to add an option for moving a rect to the bottom / top.

### PR DESCRIPTION
**Pull request by cleydyr**
Fixes #41

### CODE REVIEW

**Comment by mbaeuerle** [comment]
I just can confirm that it works for these two cases:
* Shift selecting a rect
* Deleting a rect

I think there are several cases other cases to be adapted:
* Selecting a rect without shift
* Drawing the rects (some colors might change determined by the Z position)
* Some currently unused crop maximizing functions

Maybe a more pragmatic approach would be to just add new rects at the beginning of the list. This would simplify things quite a bit and as there will be no more than a couple of rects per mergedPannel anyway the performance impact is negligible.

**Review by mbaeuerle — CHANGES_REQUESTED** [review]
See other comment

**Comment by cleydyr** [comment]
Hey, @mbaeuerle . I got your suggestion. What about the numbers printed in each crop? Is it okay to print 1 to the most recently drawn rectangle?

**Comment by mbaeuerle** [comment]
@cleydyr you're right didn't think of that. But I would just enumerate the crops in reverse (in update initialize `cropCnt` with `crops.size()` and decrease it in each iteration) to match the current behavior.

**Comment by mbaeuerle** [comment]
One thing I missed: I think the draw order is directly reverse to the selection order. The oldest rectangle should be drawn first, all others on top of it. But when checking for selection the newest one should be first. Therefore adding to my last comment I would not just to reverse the enumeration but the whole drawing part.

**Comment by cleydyr** [comment]
Hey, @mbaeuerle . So, let me try to summarise the idea.

1. the newest crop should have number 1 as its label;
2. if crop B is newer than crop A, then the label of B should be strictly lesser than the label of A;
3. if crop A and B have an overlapping area AND B is newer than A, then B should have precedence when choosing a crop based on the location of a point inside that area.
4. if crop B is newer than A, then A should be drawn _first_.

Does this get the gist of the changes?

**Comment by mbaeuerle** [comment]
Hi, @cleydyr 
Number 1 and 2 are not exactly what I intended. Newer rects should have higher numbers. This is also the current implementation on master. The first (or oldest) rect starts with number 1.
But the two other points are right.

I think it's easier to state it in another way:
From a user perspective everything stays the same except for the selection of the crops. To be specific point 3 you mentioned should be implemented:

> if crop A and B have an overlapping area AND B is newer than A, then B should have precedence when choosing a crop based on the location of a point inside that area.

So for the implementation we discussed two different possibilities:
* Store the oldest rectangle at pos 0 in the list and newer rects are appended to the end:
  In this case all operations choosing a rectangle based on click need to be reversed. Note that my [previous comment](https://github.com/mbaeuerle/Briss-2.0/pull/43#issuecomment-1065316447) `Drawing the rects (some colors might change determined by the Z position)` was incorrect for this implementation choice.
* Store the newest rectangle at pos 0 in the list, always shifting all older rects one slot
  In this case only the drawing operation needs to be reversed as older rects should be drawn first and others on top of it.

**Review by mbaeuerle — APPROVED** [review]
Very nice solution! Thanks for that 🎉

**Pull request merged**
