### PR TITLE
Support Wayland: Update javafx plugin to 0.0.13 in build.gradle.

### PR DESCRIPTION
**Pull request by camden-bock**
Added support for Wayland by updating JavaFX to 0.0.13. Tested on Pop_OS 20.04 running Wayland.

### CODE REVIEW

**Comment by cleydyr** [comment]
Hey, @camden-bock . Thanks for this PR.

I've enabled Wayland on a PopOS 20.04 VM and the master branch seems to be working just fine, so this upgrade to `javafx` seems to be unnecessary currently. Can you please expand on the rationale for this change?

**Comment by camden-bock** [comment]
Hi @cleydyr ,

Apologies if this was something specific to my system.  I am not very well versed in Java. 

I have a desktop and a laptop running PopOS 22.04 with Wayland. If it makes a difference, one has AMD graphics, the other has an integrated Intel graphics.

When starting Briss2.0, I would immediately encounter:

```Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found```

On each system, I initially tried the binary in the GitHub releases, and then built from source in JetBrains IntelliJ IDEA. I was not able to get a window to appear in either case. Updating the JavaFX version seemed to resolve the issue. I tried to find a library that might resolve this, without any success. At the time, I had found a problem with Wayland and JavaFX described in a forum, with a suggestion of using a more recent version - however I can't seem to find that now.

If changing the JavaFX version doesn't seem to be a good approach, or if this might be some quirk of the configuration of my system, please close this PR.

**Comment by cleydyr** [comment]
Hey, @mbaeuerle . I think this change is innocuous and can get through even if I couldn't reproduce the behavior on a clean environment. What do you think?

**Comment by cleydyr** [comment]
Hey, @camden-bock .

I've released a new version of Briss 2.0 alpha. Can you give it a try and see if the issue this issue is solved there?

**Comment by mbaeuerle** [comment]
Sorry for the late reply, this change should be fine! @camden-bock thanks for your contribution!

**Pull request merged**
